services:
  mysql:
    container_name: mysql1
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
