services:
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mongodb:
    container_name: mongodb
    image: mongo
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    container_name: redis
    image: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  mongo_data:
  redis_data:
